<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$enabled = $baseHelper->getConfigValue('facebookchatsection/generalgroup/enable');
if ($enabled == 1) {
    $fbPageId = $baseHelper->getConfigValue('facebookchatsection/generalgroup/fb_page_id');
    $fbThemeColor = $baseHelper->getConfigValue('facebookchatsection/generalgroup/fb_theme_color');
    $fbChatMinimized = $baseHelper->getConfigValue('facebookchatsection/generalgroup/fb_chat_minimized');
    ?>
    <div id="fb-root"></div>
    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id))
                return;
            js = d.createElement(s);
            js.id = id;
            js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <!-- Your customer chat code -->
    <div class="fb-customerchat"
         attribution="setup_tool"
         page_id="<?php echo $fbPageId; ?>" 
         <?php if ($fbChatMinimized == 1) { ?>
             minimized="true"
         <?php } ?>
         <?php if ($fbThemeColor != '') { ?>
             theme_color="<?php echo $fbThemeColor; ?>"
         <?php } ?>
         >
    </div>
<?php } ?>