<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$mediaUrl = $baseHelper->getMediaUrl();
$displayIcons = $baseHelper->getConfigValue('header_section/general/display_icons');
?>

<?php if (count($block->getStores()) > 1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="dropdown-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id ?>">
        <strong>
            <?php echo __('Language'); ?>
        </strong>
        <ul>
            <?php foreach ($block->getStores() as $_lang) : ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                        <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                            <?php if ($displayIcons == 1) { ?>
                                <span><img src="<?php echo $mediaUrl . 'language/' . $block->escapeHtml($_lang->getCode()) . '.png'; ?>" alt="<?php echo $block->escapeHtml($_lang->getCode()); ?>" /></span>
                            <?php } ?>
                            <span><?= $block->escapeHtml($_lang->getName()) ?></span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
