<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);

$imageHelper = $this->helper('Magento\Catalog\Helper\Image');

$baseHelper = $this->helper('ET\Base\Helper\Data');

$enableRating = $baseHelper->getConfigValue('category_section/general/enable_rating');
$productColumns = $baseHelper->getConfigValue('category_section/general/product_columns');
$productColumnClass = 'three-blocks';
if ($productColumns == 3) {
    $productColumnClass = 'three-blocks';
} else if ($productColumns == 4) {
    $productColumnClass = 'four-blocks';
} else if ($productColumns == 5) {
    $productColumnClass = 'five-blocks';
} else if ($productColumns == 6) {
    $productColumnClass = 'six-blocks';
}

$enableAlternateImage = $baseHelper->getConfigValue('category_section/product_image/enable_alternate_image');
$enableAspectRatio = $baseHelper->getConfigValue('category_section/product_image/enable_aspect_ratio');
$imgWidth = $baseHelper->getConfigValue('category_section/product_image/img_width');
if ($imgWidth == '') {
    $imgWidth = 350;
}
$imgHeight = $baseHelper->getConfigValue('category_section/product_image/img_height');
if ($imgHeight == '') {
    $imgHeight = 400;
}
$addImageBorder = $baseHelper->getConfigValue('category_section/product_image/add_image_border');

$enableCart = $baseHelper->getConfigValue('category_section/product_actions/enable_cart');
$displayOnlyIcon = $baseHelper->getConfigValue('category_section/product_actions/display_only_icon');
$moveCart = $baseHelper->getConfigValue('category_section/product_actions/move_cart');

$enableAddto = $baseHelper->getConfigValue('category_section/product_actions/enable_addto');
$moveAddto = $baseHelper->getConfigValue('category_section/product_actions/move_addto');

$showNewLabel = $baseHelper->getConfigValue('category_section/product_labels/show_new_label');
$showSaleLabel = $baseHelper->getConfigValue('category_section/product_labels/show_sale_label');

$imageHover = 'product_list_hover';
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else : ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <div class="list-row">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product) : ?>
                    <li class="item product <?php if ($viewMode == 'grid') { ?> product-li <?php echo $productColumnClass; ?> <?php } else { ?> product-item <?php } ?>">
                        <div class="product-item-info <?php if ($moveAddto == 1) { ?> addto-in <?php } ?> <?php if ($moveCart == 1) { ?> cart-in <?php } ?> <?php if ($displayOnlyIcon) { ?> cart-icon <?php } ?>" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <div class="pro-img">
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="<?php if ($addImageBorder) { ?> add-border <?php } ?> product photo product-item-photo" tabindex="-1">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper">
                                            <?php
                                            if ($enableAspectRatio == 1) {
                                                $productImage = $imageHelper->init($_product, $imageDisplayArea)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($imgWidth);
                                            } else {
                                                $productImage = $imageHelper->init($_product, $imageDisplayArea)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepTransparency(TRUE)->keepFrame(TRUE)->resize($imgWidth, $imgHeight);
                                            }
                                            $productImageUrl = $productImage->getUrl();
                                            ?>
                                            <img class="product-image-photo defaultImg" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                            <?php if ($enableAlternateImage == 1) { ?>
                                                <?php
                                                if ($enableAspectRatio == 1) {
                                                    $productHoverImage = $imageHelper->init($_product, $imageHover)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($imgWidth);
                                                } else {
                                                    $productHoverImage = $imageHelper->init($_product, $imageHover)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepTransparency(TRUE)->keepFrame(TRUE)->resize($imgWidth, $imgHeight);
                                                    ;
                                                }
                                                $productHoverImageUrl = $productHoverImage->getUrl();
                                                ?>
                                                <img class="hoverImg" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                            <?php } ?>
                                        </span>
                                    </span>
                                </a>
                                <?php
                                if ($showNewLabel == 1) {
                                    $fromDate = $_product->getNewsFromDate();
                                    $toDate = $_product->getNewsToDate();

                                    if (isset($fromDate) && isset($toDate)) {
                                        $fromDate = strtotime($fromDate);
                                        $toDate = strtotime($toDate);
                                        $now = strtotime(date("Y-m-d h:m:s"));

                                        if ($fromDate <= $now && $now <= $toDate) {
                                            ?>
                                            <span class="new-label"><?php echo __('New'); ?></span>
                                            <?php
                                        }
                                    }
                                }

                                if ($showSaleLabel == 1) {
                                    $special_price = number_format((float)$_product->getSpecialPrice(), 2);
                                    $regular_price = number_format((float)$_product->getPrice(), 2);
                                    if (isset($special_price) && $special_price > 0) {
                                        if ($special_price < $regular_price) {
                                            $fromSpecialDate = $_product->getSpecialFromDate();
                                            $toSpecialDate = $_product->getSpecialToDate();

                                            if (isset($fromSpecialDate) && isset($toSpecialDate)) {
                                                $fromSpecialDate = strtotime($fromSpecialDate);
                                                $toSpecialDate = strtotime($toSpecialDate);
                                                $now = strtotime(date("Y-m-d h:m:s"));

                                                if ($fromSpecialDate <= $now && $now <= $toSpecialDate) {
                                                    ?>
                                                    <span class="sale-label"><?php echo __('Sale'); ?></span>
                                                    <?php
                                                }
                                            }
                                        }
                                    }
                                }
                                ?>
                            </div>
                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                           <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?php if ($enableRating == 1) { ?>
                                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php } ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                <?php if ($_product->isAvailable()) : ?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos((string)$pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                        <?php if ($enableCart == 1) { ?>
                                            <div class="actions-primary"<?= strpos((string)$pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                <?php if ($_product->isSaleable()) : ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form"
                                                          data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                                          action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                          method="post">
                                                        <input type="hidden"
                                                               name="product"
                                                               value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                               value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                               <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                class="action tocart primary <?php if ($displayOnlyIcon) { ?> only-icon <?php } ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else : ?>
                                                    <?php if ($_product->isAvailable()) : ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php } ?>
                                        <?php if ($enableAddto == 1) { ?>
                                            <div data-role="add-to-links" class="actions-secondary"<?= strpos((string)$pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php } ?>
                                    </div>
                                    <?php if ($showDescription) : ?>
                                        <div class="product description product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                               title="<?= /* @noEscape */ $_productNameStripped ?>"
                                               class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
            "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
            }
            }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>