<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$enableAddto = $baseHelper->getConfigValue('product_section/general/enable_addto');
if ($enableAddto == 1) {
    ?>
    <div class="product-addto-links" data-role="add-to-links">
        <?= $block->getChildHtml() ?>
    </div>
<?php } ?>