<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$enabled = $baseHelper->getConfigValue('productstocksection/generalgroup/enabled');
if ($enabled == 1) {
    $_product = $block->getProduct();
    $productType = $_product->getTypeId();
    
    if ($productType == 'simple' || $productType == 'virtual' || $productType == 'downloadable') {

        // Get Product Quantity
        $stockItem = $_product->getExtensionAttributes()->getStockItem();
        $productQty = $stockItem->getQty();

        $productQuantity = $baseHelper->getConfigValue('productstocksection/generalgroup/product_quantity');
        $productQuantity = trim($productQuantity);
        $messageText = $baseHelper->getConfigValue('productstocksection/generalgroup/message_text');
        $displayProgressbar = $baseHelper->getConfigValue('productstocksection/generalgroup/display_progressbar');

        if ($productQty <= $productQuantity) {
            $percentageVal = ($productQty * 100) / $productQuantity;
            ?>
            <div class="product-qty-wrapper">
                <div class="message-text"><?php echo __($messageText, $productQty); ?></div>
                <?php if ($displayProgressbar == 1) { ?>
                    <div class="progressbar-block">
                        <span class="outer-bar">
                            <span class="inner-bar" style="max-width: <?php echo $percentageVal . '%'; ?>;"></span>
                        </span>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    <?php } ?>
<?php } ?>