<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related <i>Products</i>');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related <i>Products</i>');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products <i>you might like!</i>');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products <i>you might like!</i>');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More <i>Choices:</i>');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More <i>Choices:</i>');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New <i>Products</i>');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist): ?>
    <?php
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');

    $baseHelper = $this->helper('ET\Base\Helper\Data');

    $enableRating = $baseHelper->getConfigValue('category_section/general/enable_rating');

    $enableAlternateImage = $baseHelper->getConfigValue('category_section/product_image/enable_alternate_image');
    $enableAspectRatio = $baseHelper->getConfigValue('category_section/product_image/enable_aspect_ratio');
    $imgWidth = $baseHelper->getConfigValue('category_section/product_image/img_width');
    if ($imgWidth == '') {
        $imgWidth = 350;
    }
    $imgHeight = $baseHelper->getConfigValue('category_section/product_image/img_height');
    if ($imgHeight == '') {
        $imgHeight = 400;
    }
    $addImageBorder = $baseHelper->getConfigValue('category_section/product_image/add_image_border');

    $enableCart = $baseHelper->getConfigValue('category_section/product_actions/enable_cart');
    $displayOnlyIcon = $baseHelper->getConfigValue('category_section/product_actions/display_only_icon');
    $moveCart = $baseHelper->getConfigValue('category_section/product_actions/move_cart');

    $enableAddto = $baseHelper->getConfigValue('category_section/product_actions/enable_addto');
    $moveAddto = $baseHelper->getConfigValue('category_section/product_actions/move_addto');

    $showNewLabel = $baseHelper->getConfigValue('category_section/product_labels/show_new_label');
    $showSaleLabel = $baseHelper->getConfigValue('category_section/product_labels/show_sale_label');

    $imageHover = 'product_list_hover';

    $randomNum = rand(1000, 1000000);

    $enableSlider = 1;

    $productColumnClass = '';
    if ($enableSlider == 1) {
        $productColumnClass = 'slider-li';
    } else {
        $productColumnClass = 'five-blocks';
    }
    ?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= $block->escapeHtmlAttr($class) ?>"
                 data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
                 data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
                 <?php else: ?>
                <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"upsellProducts":{}}'
                     data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
                     <?php endif; ?>
                 <?php else: ?>
                <div class="block <?= $block->escapeHtmlAttr($class) ?>">
                <?php endif; ?>
                <div class="section-title">
                    <span id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading"
                          aria-level="2"><?= htmlspecialchars_decode($title) ?></span>
                </div>
                <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                    <?php if ($type == 'related' && $canItemsAddToCart): ?>
                        <div class="block-actions">
                            <?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
                            <button type="button" class="action select"
                                    data-role="select-all"><span><?= $block->escapeHtml(__('select all')) ?></span></button>
                        </div>
                    <?php endif; ?>
                    <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                        <div class="list-row">
                            <ol class="products list items product-items <?php if ($enableSlider == 1) { ?> related-upsell-slider owl-carousel owl-theme <?php } ?>">
                                <?php foreach ($items as $_item): ?>
                                    <?php $available = ''; ?>
                                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                        <?php if (!$_item->getRequiredOptions()): ?>
                                            <?php $available = 'related-available'; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                                        <li class="product-li <?php echo $productColumnClass; ?>">
                                        <?php else: ?>
                                        <li class="product-li <?php echo $productColumnClass; ?>">
                                        <?php endif; ?>
                                        <div class="product-item-info <?= /* @noEscape */ $available ?> <?php if ($moveAddto == 1) { ?> addto-in <?php } ?> <?php if ($moveCart == 1) { ?> cart-in <?php } ?> <?php if ($displayOnlyIcon) { ?> cart-icon <?php } ?>">
                                            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                            <div class="pro-img">
                                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="<?php if ($addImageBorder) { ?> add-border <?php } ?> product photo product-item-photo">
                                                    <span class="product-image-container">
                                                        <span class="product-image-wrapper">
                                                            <?php
                                                            if ($enableAspectRatio == 1) {
                                                                $productImage = $imageHelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($imgWidth);
                                                            } else {
                                                                $productImage = $imageHelper->init($_item, $image)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepTransparency(TRUE)->keepFrame(TRUE)->resize($imgWidth, $imgHeight);
                                                            }
                                                            $productImageUrl = $productImage->getUrl();
                                                            ?>
                                                            <img class="product-image-photo defaultImg" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                                            <?php if ($enableAlternateImage == 1) { ?>
                                                                <?php
                                                                if ($enableAspectRatio == 1) {
                                                                    $productHoverImage = $imageHelper->init($_item, $imageHover)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($imgWidth);
                                                                } else {
                                                                    $productHoverImage = $imageHelper->init($_item, $imageHover)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepTransparency(TRUE)->keepFrame(TRUE)->resize($imgWidth, $imgHeight);
                                                                    ;
                                                                }
                                                                $productHoverImageUrl = $productHoverImage->getUrl();
                                                                ?>
                                                                <img class="hoverImg" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                                            <?php } ?>
                                                        </span>
                                                    </span>
                                                </a>
                                                <?php
                                                if ($showNewLabel == 1) {
                                                    $fromDate = $_item->getNewsFromDate();
                                                    $toDate = $_item->getNewsToDate();

                                                    if (isset($fromDate) && isset($toDate)) {
                                                        $fromDate = strtotime($fromDate);
                                                        $toDate = strtotime($toDate);
                                                        $now = strtotime(date("Y-m-d h:m:s"));

                                                        if ($fromDate <= $now && $now <= $toDate) {
                                                            ?>
                                                            <span class="new-label"><?php echo __('New'); ?></span>
                                                            <?php
                                                        }
                                                    }
                                                }

                                                if ($showSaleLabel == 1) {
                                                    $special_price = number_format((float)$_item->getSpecialPrice(), 2);
                                                    $regular_price = number_format((float)$_item->getPrice(), 2);
                                                    if (isset($special_price) && $special_price > 0) {
                                                        if ($special_price < $regular_price) {
                                                            $fromSpecialDate = $_item->getSpecialFromDate();
                                                            $toSpecialDate = $_item->getSpecialToDate();

                                                            if (isset($fromSpecialDate) && isset($toSpecialDate)) {
                                                                $fromSpecialDate = strtotime($fromSpecialDate);
                                                                $toSpecialDate = strtotime($toSpecialDate);
                                                                $now = strtotime(date("Y-m-d h:m:s"));

                                                                if ($fromSpecialDate <= $now && $now <= $toSpecialDate) {
                                                                    ?>
                                                                    <span class="sale-label"><?php echo __('Sale'); ?></span>
                                                                    <?php
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                                ?>
                                            </div>
                                            <div class="product details product-item-details">
                                                <strong class="product name product-item-name"><a
                                                        class="product-item-link"
                                                        title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                        href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                                        <?= $block->escapeHtml($_item->getName()) ?></a>
                                                </strong>

                                                <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                                <?php if ($enableRating == 1) { ?>
                                                    <?php if ($templateType): ?>
                                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                                    <?php endif; ?>
                                                <?php } ?>
                                                <div class="product-item-inner">
                                                    <?php if ($enableCart == 1) { ?>
                                                        <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'):
                                                            ?>
                                                            <?php if (!$_item->getRequiredOptions()): ?>
                                                                <div class="field choice related"><input
                                                                        type="checkbox"
                                                                        class="checkbox related"
                                                                        id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                                                        name="related_products[]"
                                                                        value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                                                    <label
                                                                        class="label"
                                                                        for="related-checkbox<?=
                                                                        $block->escapeHtmlAttr(
                                                                                $_item->getId()
                                                                        )
                                                                        ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </label>
                                                                </div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    <?php } ?>

                                                    <?php if ($showAddTo || $showCart): ?>
                                                        <?php // phpcs:disable ?>
                                                        <div class="product actions product-item-actions">
                                                            <?php if ($enableCart == 1) { ?>
                                                                <?php if ($showCart): ?>
                                                                    <?php if ($_item->isSaleable()): ?>
                                                                        <div class="actions-primary">
                                                                            <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                                                <button
                                                                                    class="action tocart primary"
                                                                                    data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                                </button>
                                                                            <?php else : ?>
                                                                                <?php
                                                                                /** @var $viewModel PreparePostData */
                                                                                $viewModel = $block->getViewModel();
                                                                                $postArray = $viewModel->getPostData(
                                                                                        $block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()]
                                                                                );
                                                                                $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                                                ?>
                                                                                <form data-role="tocart-form"
                                                                                      data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                                                      action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                                      method="post">
                                                                                    <input type="hidden" name="product"
                                                                                           value="<?= /* @noEscape */ (int) $_item->getEntityId() ?>">
                                                                                    <input type="hidden"
                                                                                           name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                                                           value="<?= /* @noEscape */ $value ?>">
                                                                                           <?= $block->getBlockHtml('formkey') ?>
                                                                                    <button type="submit"
                                                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                                            class="action tocart primary">
                                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                                    </button>
                                                                                </form>
                                                                            <?php endif; ?>
                                                                        <?php else: ?>
                                                                            <?php if ($_item->getIsSalable()): ?>
                                                                                <div class="stock available">
                                                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                                </div>
                                                                            <?php else: ?>
                                                                                <div class="stock unavailable">
                                                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                                </div>
                                                                            <?php endif; ?>
                                                                        <?php endif; ?>
                                                                    </div>
                                                                <?php endif; ?>
                                                            <?php } ?>
                                                            <?php if ($enableAddto == 1) { ?>
                                                                <?php if ($showAddTo): ?>
                                                                    <div class="secondary-addto-links actions-secondary"
                                                                         data-role="add-to-links">
                                                                             <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                                                 <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                                             <?php endif; ?>
                                                                    </div>
                                                                <?php endif; ?>
                                                            <?php } ?>
                                                        </div>
                                                        <?php // phpcs:enable ?>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach ?>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <?php if (!$block->isRedirectToCartEnabled() && $_item): ?>
                <script type="text/x-magento-init">
                    {
                    "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                    }
                    }
                </script>
            <?php endif; ?>
        <?php endif; ?>
