<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

    $title = __($block->getTitle());

    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');

    $baseHelper = $this->helper('ET\Base\Helper\Data');

    $enableRating = $baseHelper->getConfigValue('category_section/general/enable_rating');

    $enableAlternateImage = $baseHelper->getConfigValue('category_section/product_image/enable_alternate_image');
    $enableAspectRatio = $baseHelper->getConfigValue('category_section/product_image/enable_aspect_ratio');
    $imgWidth = $baseHelper->getConfigValue('category_section/product_image/img_width');
    if ($imgWidth == '') {
        $imgWidth = 350;
    }
    $imgHeight = $baseHelper->getConfigValue('category_section/product_image/img_height');
    if ($imgHeight == '') {
        $imgHeight = 400;
    }
    $addImageBorder = $baseHelper->getConfigValue('category_section/product_image/add_image_border');

    $enableCart = $baseHelper->getConfigValue('category_section/product_actions/enable_cart');
    $displayOnlyIcon = $baseHelper->getConfigValue('category_section/product_actions/display_only_icon');
    $moveCart = $baseHelper->getConfigValue('category_section/product_actions/move_cart');

    $enableAddto = $baseHelper->getConfigValue('category_section/product_actions/enable_addto');
    $moveAddto = $baseHelper->getConfigValue('category_section/product_actions/move_addto');

    $showNewLabel = $baseHelper->getConfigValue('category_section/product_labels/show_new_label');
    $showSaleLabel = $baseHelper->getConfigValue('category_section/product_labels/show_sale_label');

    $imageHover = 'product_list_hover';

    $randomNum = rand(1000, 1000000);

    $enableSlider = $baseHelper->getConfigValue('category_section/general/enable_featured');

    $productColumnClass = '';
    if ($enableSlider == 1) {
        $productColumnClass = 'slider-li';
    } else {
        $productColumnClass = 'five-blocks';
    }
    ?>
    <div class="block widget block-products-list widget-products-section <?php if ($enableSlider == 1) { ?> slider-enabled <?php } ?> <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="section-title">
                <span><?= htmlspecialchars_decode($title) ?></span>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <div class="list-row">
                    <ol class="product-items <?= /* @noEscape */ $type ?> <?php if ($enableSlider == 1) { ?> catalog-widget-slider owl-carousel owl-theme <?php } ?>">
                        <?php foreach ($items as $_item) : ?>
                            <li class="product-li <?php echo $productColumnClass; ?>">
                                <div class="product-item-info <?php if ($moveAddto == 1) { ?> addto-in <?php } ?> <?php if ($moveCart == 1) { ?> cart-in <?php } ?> <?php if ($displayOnlyIcon) { ?> cart-icon <?php } ?>">
                                    <div class="pro-img">
                                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="<?php if ($addImageBorder) { ?> add-border <?php } ?> product photo product-item-photo">
                                            <span class="product-image-container">
                                                <span class="product-image-wrapper">
                                                    <?php
                                                    if ($enableAspectRatio == 1) {
                                                        $productImage = $imageHelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($imgWidth);
                                                    } else {
                                                        $productImage = $imageHelper->init($_item, $image)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepTransparency(TRUE)->keepFrame(TRUE)->resize($imgWidth, $imgHeight);
                                                    }
                                                    $productImageUrl = $productImage->getUrl();
                                                    $cleanUrl = str_replace('\\cache\8c4de0085286027621edb4847abd4b1f\\', '', $productImageUrl);
                                                    ?>
                                                    <img class="product-image-photo defaultImg" src="<?php echo $cleanUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                                    <?php if ($enableAlternateImage == 1) { ?>
                                                        <?php
                                                        if ($enableAspectRatio == 1) {
                                                            $productHoverImage = $imageHelper->init($_item, $imageHover)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($imgWidth);
                                                        } else {
                                                            $productHoverImage = $imageHelper->init($_item, $imageHover)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepTransparency(TRUE)->keepFrame(TRUE)->resize($imgWidth, $imgHeight);
                                                            ;
                                                        }
                                                        $productHoverImageUrl = $productHoverImage->getUrl();
                                                        ?>
                                                        <img class="hoverImg" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                                    <?php } ?>
                                                </span>
                                            </span>
                                        </a>
                                        <?php
                                        if ($showNewLabel == 1) {
                                            $fromDate = $_item->getNewsFromDate();
                                            $toDate = $_item->getNewsToDate();

                                            if (isset($fromDate) && isset($toDate)) {
                                                $fromDate = strtotime($fromDate);
                                                $toDate = strtotime($toDate);
                                                $now = strtotime(date("Y-m-d h:m:s"));

                                                if ($fromDate <= $now && $now <= $toDate) {
                                                    ?>
                                                    <span class="new-label"><?php echo __('New'); ?></span>
                                                    <?php
                                                }
                                            }
                                        }

                                        if ($showSaleLabel == 1) {
                                            $special_price = number_format((float)$_item->getSpecialPrice(), 0);
                                            $regular_price = number_format((float)$_item->getPrice(), 2);
                                            if (isset($special_price) && $special_price > 0) {
                                                if ($special_price < $regular_price) {
                                                    $fromSpecialDate = $_item->getSpecialFromDate();
                                                    $toSpecialDate = $_item->getSpecialToDate();

                                                    if (isset($fromSpecialDate) && isset($toSpecialDate)) {
                                                        $fromSpecialDate = strtotime($fromSpecialDate);
                                                        $toSpecialDate = strtotime($toSpecialDate);
                                                        $now = strtotime(date("Y-m-d h:m:s"));

                                                        if ($fromSpecialDate <= $now && $now <= $toSpecialDate) {
                                                            ?>
                                                            <span class="sale-label"><?php echo __('Sale'); ?></span>
                                                            <?php
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        ?>
                                    </div>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                   <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php if ($enableRating == 1) { ?>
                                            <?php if ($templateType) : ?>
                                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                            <?php endif; ?>
                                        <?php } ?>

                                        <?= $block->getProductPriceHtml($_item, $type) ?>

                                        <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <?php if ($enableCart == 1) { ?>
                                                        <?php if ($showCart) : ?>
                                                            <div class="actions-primary">
                                                                <?php if ($_item->isSaleable()) : ?>
                                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                                    <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                        <?= $block->getBlockHtml('formkey') ?>
                                                                        <button type="submit"
                                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                                class="action tocart primary <?php if ($displayOnlyIcon) { ?> only-icon <?php } ?>">
                                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                        </button>
                                                                    </form>
                                                                <?php else : ?>
                                                                    <?php if ($_item->getIsSalable()) : ?>
                                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                                    <?php else : ?>
                                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                                    <?php endif; ?>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php } ?>
                                                    <?php if ($enableAddto == 1) { ?>
                                                        <?php if ($showWishlist || $showCompare) : ?>
                                                            <div class="actions-secondary" data-role="add-to-links">
                                                                <?php //phpcs:disable ?>
                                                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                                    <?php //phpcs:enable  ?>
                                                                    <a href="#"
                                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                    </a>
                                                                <?php endif; ?>
                                                                <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                                    <?php //phpcs:disable ?>
                                                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                                                    <?php //phpcs:enable  ?>
                                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                    </a>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>