<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Checkout\Block\Onepage */
?>
<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$enableCheckoutDesign = $baseHelper->getConfigValue('checkout_section/general/enabled');
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div class="checkout-container-inner">
        <?php if ($enableCheckoutDesign == 1) { ?>
            <div class="logo-block">
                <?php echo $this->getChildHtml('new.checkout.logo'); ?>
            </div>
        <?php } ?>
        <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
            <div class="loader">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                     alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                     style="position: absolute;">
            </div>
        </div>
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
            "#checkout": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
            }
        </script>
        <script>
            window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
            // Create aliases for customer.js model from customer module
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            window.customerData = window.checkoutConfig.customerData;
        </script>
        <script>
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function (url, blockLoader) {
                blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
                return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
            })
        </script>
    </div>
</div>